### ISSUE TITLE
How to use custom Ecto type for `item_id` 

### ISSUE THREAD

**Issue by mayel** [izelnakri/paper_trail#235]
Hi, thanks for merging my recent PR :)
It's great that we can configure the type of ID used for `item_id`, but an issue for us is that it doesn't seem to work for types that aren't built-in to Ecto (such as `Needle.ULID` from https://www.hex.pm/packages/needle_ulid). What would be a good approach to make this possible (without simply adding such libraries as an optional dependency)?

**Comment by izelnakri** [comment]
Hi @mayel ,

I've never come across this issue before. What kind of error do you get? Perhaps we can simulate the scenario in a test and then create a solution/PR for this edge case scenario.

**Comment by mayel** [comment]
Here's a basic reproduction which results in the following compilation error: https://github.com/bonfire-networks/paper_trail/tree/custom-type-repro/example
```
== Compilation error in file lib/version.ex ==
** (ArgumentError) unknown type Needle.ULID for field :item_id
    (ecto 3.12.3) lib/ecto/schema.ex:2491: Ecto.Schema.check_field_type!/4
    (ecto 3.12.3) lib/ecto/schema.ex:2053: Ecto.Schema.__field__/4
    lib/version.ex:18: (module)
```

**Comment by izelnakri** [comment]
Hi again @mayel sorry for getting back bit late. Could you provide a test reproduction as a test case in this repository? Then we can check/discuss it in depth and perhaps find a solution.

**Comment by GuilAFT** [comment]
I have the same issue. to reproduce it,  edit your config.exs:

```
config :paper_trail,
  repo: YourApp.Repo,
  originator_type: TypeID
  item_type: TypeID
```

TypeID is a custom type provided by: (https://hexdocs.pm/elixir_typeid/readme.html)
Just like @mayel 's custom type

Then, recompile making sure you delete the already compiled library:

`$ rm -rf deps/paper_trail && mix deps.get && mix compile`

This should result in the error:

```
==> paper_trail
Compiling 7 files (.ex)

== Compilation error in file lib/version.ex ==
** (ArgumentError) unknown type TypeID for field :item_id
    (ecto 3.13.5) lib/ecto/schema.ex:2567: Ecto.Schema.check_field_type!/4
    (ecto 3.13.5) lib/ecto/schema.ex:1985: Ecto.Schema.__field__/4
    lib/version.ex:18: (module)
could not compile dependency :paper_trail, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile paper_trail --force", update it with "mix deps.update paper_trail" or clean it with "mix deps.clean paper_trail"
```

This likely happens because `PaperTrail` doesn't have access to the custom id type (`TypeID`) at the type of compilation.

Note that using the underlying type (`:string` in this case), doesn't work and returns this error: 

```
 ** (Ecto.ChangeError) value `#TypeID<"user_01kew92efae75rz8xzgzh26wrv">` for `PaperTrail.Version.originator_id` in `insert` does not match type :string
```

I'm trying to solve this without making my own PaperTrail fork, but I wasn't able yet.

@izelnakri, do you have any ideas on how could this be fixed?

**Comment by GuilAFT** [comment]
UPDATE: I've made a fork that works with TypeID

@mayel, this might be a solution for you: https://github.com/GuilAFT/paper_trail

It's pretty dodgy to do this tho.

Would love to get some feedback from @izelnakri on what could be done to support custom types from other libraries.

**Comment by mayel** [comment]
Thanks @GuilAFT, yeah we do something similar: https://github.com/izelnakri/paper_trail/compare/main...bonfire-networks:paper_trail:with-pointers but would love to not have to use a fork either!

**Comment by mayel** [comment]
@izelnakri @GuilAFT here's a possible approach: https://github.com/izelnakri/paper_trail/pull/255
