### ISSUE TITLE
error when trying update post with nested fields

### ISSUE THREAD

**Issue by MeterSoft** [izelnakri/paper_trail#46]
When i edit and save post with nested fields without change base post fields papertrail return error
```
** (Poison.EncodeError) unable to encode value: {"does not exist", []}
    (poison) lib/poison/encoder.ex:383: Poison.Encoder.Any.encode/2
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:259: anonymous fn/3 in Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:260: Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:259: anonymous fn/3 in Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:260: Poison.Encoder.List.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison.ex:41: Poison.encode!/2
    (ecto) /home/bohdan/work/three_taps/deps/postgrex/lib/postgrex/type_module.ex:715: Ecto.Adapters.Postgres.TypeModule.encode_params/3
    (postgrex) lib/postgrex/query.ex:45: DBConnection.Query.Postgrex.Query.encode/3
    (db_connection) lib/db_connection.ex:1079: DBConnection.describe_run/5
    (db_connection) lib/db_connection.ex:1150: anonymous fn/4 in DBConnection.run_meter/5
    (db_connection) lib/db_connection.ex:592: DBConnection.prepare_execute/4

```

When i update record without papertrail it works well.

my changeset

```
#Ecto.Changeset<action: nil,
 changes: %{images: [#Ecto.Changeset<action: :insert,
     changes: %{delete: false,
       url: %{file_name: "Screenshot_2018-03-21-19-50-05-445_ua.slando.png",
         updated_at: #Ecto.DateTime<2018-06-15 11:39:45>},
       uuid: "c8e65420-7090-11e8-982b-c85b76d3a09f"}, errors: [],
     data: #Olist.Images.Image<>, valid?: true>]}, errors: [],
 data: #Olist.Postings.Posting<>, valid?: true>

```

to save use
```
posting
    |> Posting.changeset(attrs)
    |> PaperTrail.update(user: user)
```

**Comment by izelnakri** [comment]
Could you post your model schema? PaperTrail currently does not support nested relationship versioning on purpose, if this is what you were trying to do. I suggest inserting them in a flat transaction: https://github.com/izelnakri/paper_trail/issues/39.
