### ISSUE TITLE
(FunctionClauseError) no function clause matching in Regex.safe_run/3 on mix deps.get

### ISSUE THREAD

**Issue by naumoski** [izelnakri/paper_trail#58]
Getting this error when trying to get the dependencies
`
** (FunctionClauseError) no function clause matching in Regex.safe_run/3    
    
    The following arguments were given to Regex.safe_run/3:
    
        # 1
        ~r/\/\/([^:]*):[^@]+@/
    
        # 2
        "https://repo.hex.pm/tarballs/phoenix-1.4.9.tar"
    
        # 3
        [{:capture, :all, :index}, :global]
    
    Attempted function clauses (showing 1 out of 1):
    
        defp safe_run(%Regex{re_pattern: compiled, source: source, re_version: version}, string, options)
    
    (elixir) lib/regex.ex:463: Regex.safe_run/3
    (elixir) lib/regex.ex:663: Regex.do_replace/4
    (hex) lib/hex/scm.ex:109: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:176: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
    (mix) lib/mix/dep/converger.ex:108: Mix.Dep.Converger.all/4
`

**Comment by naumoski** [comment]
Sorry my bad, you can close this issue
